apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2
  labels:
    app: oauth2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2
  template:
    metadata:
      labels:
        app: oauth2
    spec:
      containers:
      - name: oauth2
        image: yassiin/oauth2:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: oauth2-service
spec:
  selector:
    app: oauth2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ouath2-vs
spec:
  hosts:
  - "*"
  gateways:
  - istio-gateway
  http:
  - route:
    - destination:
        host: oauth2-service
        port:
          number: 80
    match:
    - uri:
        prefix: /auth/
    rewrite:
      uri: /

