spring:
  application:
    name: PaymentService
  datasource:
    url: jdbc:postgresql://localhost:5432/payment-service
    username: postgres
    password: postgres

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 9093

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  kafka:
    bootstrap-servers: localhost:29092
    client-id: kafka-axon-example
    default-topic: local.event
    properties:
      security.protocol: PLAINTEXT

    publisher:
      confirmation-mode: none

    producer:
#      transaction-id-prefix: kafka-sample
      retries: 5
      event-processor-mode: tracking
#      properties:
#        enable.idempotence: true
#        acks: all


    fetcher:
      poll-timeout: 3000

    consumer:
      enable-auto-commit: true
      auto-commit-interval: 3000
      event-processor-mode: tracking
