apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb-postgresql-ha-pgpool:5432/helm"
  SPRING_DATASOURCE_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_DATASOURCE_JPA_SHOW_SQL: "true"
  SPRING_DATASOURCE_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_DATASOURCE_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"